### ISSUE TITLE
Missing code of conduct

### ISSUE THREAD

**Issue by sinetris** [elixir-berlin/elixir-berlin.github.io#5]
I realised only now that we don't have a code of conduct on the website 😱 
We should add a link to http://berlincodeofconduct.org/ and make a PR to https://github.com/rubyberlin/code-of-conduct#add-your-user-groupconference-to-the-list

@duksis what do you think?

**Comment by duksis** [comment]
we should and we appreciate any help in improving the meetup :)

**Comment by dominicletz** [comment]
I've added a link now to our website pointing to this: https://github.com/elixir-berlin/planning/blob/main/Code-of-Conduct.md

But it seems to me it's the same content no? I guess we can just reference the ruby one
